name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/Desktop/projects/wedding-card/wedding-invitation
            git pull origin main
            docker build -t wedding-invitation .
            docker stop wedding-invitation || true
            docker rm wedding-invitation || true
            docker run -d -p 8080:80 --name wedding-invitation wedding-invitation
